name: PR CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: NPM CI
        run: npm ci

      - name: Build and package
        run: npm run package:prod && npm run package:debug

      - name: Test
        run: npm run test
