name: Release CI
on:
  push:
    branches: [ release/* ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare system path for running python
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        #TODO: change to 1 and then get all tags seperately to see if that's faster. git fetch origin 'refs/tags/*:refs/tags/*'
      
      - name: NPM CI
        run: npm ci

      - name: Build and package
        run: npm run package:prod && npm run package:debug

      - name: list
        run: ls -R

        #TODO: Edge auto-deployment
